media:
  input: portfolio
  output: /portfolio

collections:
  - name: projects
    label: Projects
    label_singular: Project
    file: projects.json
    fields:
      - name: projects
        label: Projects List
        widget: list
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Description, name: description, widget: text }
          - label: Category
            name: category
            widget: select
            options:
              - { label: Sustainable Energy Solutions, value: solar }
              - { label: Safety and PPE, value: safety }
              - { label: Agriculture, value: agriculture }
              - { label: Civil & Real Estate, value: civil }
              - { label: Renewable Energy & PUEs, value: energy }
          - { label: Image, name: image, widget: image }
          - { label: Full Image (optional), name: fullImage, widget: image, required: false }